"""V3.45 SEO/ad expansion pages for Terramorph.

This module is called by build_pages.py after the base site generation. It keeps
high-volume local SEO/ad pages out of the core generator while still making the
build reproducible.
"""


def generate(ctx):
    root = ctx['root']
    page = ctx['page']
    schema_for = ctx['schema_for']
    quote_form = ctx['quote_form']
    trust_band = ctx['trust_band']
    review_stack = ctx['review_stack']
    faq_section = ctx['faq_section']
    meta_landing_page = ctx['meta_landing_page']
    PHONE = ctx['PHONE']
    TEL = ctx['TEL']
    BASE_URL = ctx['BASE_URL']
    DEFAULT_FAQS = ctx['DEFAULT_FAQS']

    cities = ['Sylvania', 'Bowling Green', 'Holland', 'Waterville', 'Whitehouse', 'Oregon', 'Rossford']
    notes = {
        'Sylvania': 'mature neighborhoods, shaded lawns, established beds, and curb appeal upgrades near Toledo-area homes',
        'Bowling Green': 'open lots, rental and owner-occupied properties, wind exposure, campus-area maintenance needs, and flat drainage conditions',
        'Holland': 'suburban yards, commercial frontage, bed refreshes, maintenance routes, and drainage patterns around drives and patios',
        'Waterville': 'river-area moisture patterns, wooded lots, established neighborhoods, and outdoor living upgrades that need careful water planning',
        'Whitehouse': 'larger yards, new construction edges, bed installation, lawn maintenance, and practical drainage planning',
        'Oregon': 'lake-effect weather, flat lots, commercial frontage, wet yards, and seasonal maintenance needs',
        'Rossford': 'older lots, compact yards, patio transitions, front-bed curb appeal, and runoff around drives or garages',
    }
    service_defs = [
        ('Landscape Design', 'landscaping', 'landscaping', 'Landscape design, bed refreshes, plantings, mulch, rock, cleanup, lighting coordination, and curb appeal planning', 'real-entry.webp?v=3.14'),
        ('Paver Patios and Hardscapes', 'paver-patios', 'paver patios', 'Paver patios, walkways, steps, seating areas, hardscape upgrades, fire pit areas, and outdoor living plans', 'real-patio.webp?v=3.14'),
        ('Drainage Solutions', 'drainage-solutions', 'drainage solutions', 'Standing water diagnosis, downspout routing, grading review, low-spot fixes, and drainage planning', 'real-drainage.webp'),
        ('Lawn Maintenance', 'lawn-maintenance', 'lawn maintenance', 'Mowing, trimming, edging, bed upkeep, cleanup support, and recurring property presentation', 'real-lawn.webp'),
    ]

    extra_city_pages = []
    for city in cities:
        city_slug = city.lower().replace(' ', '-')
        for service, service_slug, keyword_service, service_copy, image in service_defs:
            filename = f'{service_slug}-{city_slug}-ohio.html'
            headline = f'{service} in {city}, Ohio for properties that need a clearer outdoor plan.'
            lead = f'Terramorph helps {city} homeowners and property owners with {service_copy.lower()} backed by free estimates and phone-first follow-up.'
            angle = f'{city} projects often involve {notes[city]}. Terramorph reviews grade, access, water movement, materials, photos, and timeline before recommending a scope.'
            faqs = [
                (f'Does Terramorph offer {keyword_service} in {city}?', f'Yes. Terramorph serves {city} and nearby Northwest Ohio areas with {keyword_service} and related outdoor property work.'),
                ('Can I request a free estimate by phone?', f'Yes. Call Terramorph at {PHONE} with the service need, property details, photos if available, and timeline.'),
                ('Can photos be included with the request?', 'Yes. Photos are helpful because they show access, grade, existing conditions, water movement, beds, lawn areas, or hardscape details before follow-up.'),
            ]
            desc = f'Terramorph provides {keyword_service} in {city}, Ohio with free estimates for homeowners, businesses, and property owners.'
            body = f'''
<section class="page-hero premium-page-hero city-service-hero">
  <div class="page-hero-image"><img src="assets/{image}" alt="Terramorph {service} in {city}, Ohio"></div><div class="hero-overlay"></div>
  <div class="container page-hero-content"><p class="crumb"><a href="index.html">Home</a> / <a href="service-areas.html">Service Areas</a> / {city} {service}</p><p class="eyebrow light">{keyword_service} in {city}, Ohio</p><h1>{headline}</h1><p>{lead}</p><div class="cta-row"><a class="btn btn-gold" href="#quote">Request a {city} Estimate</a><a class="btn btn-outline-light" href="tel:{TEL}">Call {PHONE}</a></div></div>
</section>
{trust_band()}
<section class="section"><div class="container local-grid"><div><p class="eyebrow">Local fit</p><h2>{city} outdoor work needs local judgment.</h2><p>{angle}</p><p>These local pages help homeowners understand the Terramorph services available in their city before requesting an estimate.</p></div><div class="authority-list"><div><b>Property review</b><span>Service need, city, address, photos, timeline, and visible site conditions.</span></div><div><b>Connected services</b><span>Drainage, patios, beds, lighting, cleanups, and maintenance can be scoped together when it makes sense.</span></div><div><b>Northwest Ohio conditions</b><span>Clay soil, flat lots, freeze-thaw, and heavy rain are considered before recommendations.</span></div><div><b>Fast follow-up</b><span>Quote requests include the details the team needs to respond with the right next step.</span></div></div></div></section>
{faq_section(faqs)}
<section class="section quote-section"><div class="container quote-grid">{quote_form('Request a ' + city + ' ' + service + ' Estimate')}<div class="cta-proof"><p class="eyebrow">Fast estimate path</p><h2>Call with photos, timeline, and service details ready.</h2>{review_stack(2)}</div></div></section>
'''
            short_title = f'{service.replace(" and Hardscapes", "")} in {city}, OH | Terramorph'
            (root / filename).write_text(page(short_title, desc, body, schema_for(filename, headline, desc, faqs, service)))
            extra_city_pages.append(filename)

    case_studies = [
        ('perrysburg-paver-patio-case-study.html','Perrysburg','Paver Patios and Hardscapes','Perrysburg Paver Patio Planning Example','The backyard needed a better place to grill, sit, and connect the house to the lawn without creating drainage or freeze-thaw problems.','Terramorph reviews door transitions, base prep, water movement, access, seating layout, edge restraint, lighting options, and how the patio should tie into beds and lawn.','A clearer patio scope gives the homeowner a usable outdoor living area, cleaner flow, and fewer surprises before installation.','real-patio.webp?v=3.14'),
        ('maumee-yard-drainage-case-study.html','Maumee','Drainage Solutions','Maumee Yard Drainage Planning Example','Water was collecting after rain near low lawn areas, bed edges, and hardscape transitions where Northwest Ohio clay soil slowed drying.','Terramorph traces water sources, downspout paths, grade, discharge options, and whether grading, swales, buried lines, or bed changes make sense.','A practical drainage plan moves water intentionally instead of guessing at a single product.','real-drainage.webp'),
        ('toledo-front-yard-curb-appeal-case-study.html','Toledo','Landscape Design','Toledo Front Yard Curb Appeal Planning Example','The front beds looked tired and disconnected from the entry, making the home feel less finished from the street.','Terramorph evaluates bed shape, plant selection, mulch or rock, edging, lighting, maintenance expectations, and how the front walk should feel.','A cleaner first impression with a landscape scope that is easier to maintain and better matched to the house.','real-entry.webp?v=3.14'),
        ('sylvania-landscape-bed-refresh-case-study.html','Sylvania','Landscape Design','Sylvania Landscape Bed Refresh Planning Example','Mature plantings and older bed edges needed a reset without making the property look overbuilt or hard to maintain.','Terramorph reviews sun and shade, soil, existing plant health, bed depth, mulch versus rock, pruning, and replacement planting options.','A cleaner bed design preserves what works and updates what looks dated.','real-entry.webp?v=3.14'),
        ('bowling-green-lawn-maintenance-case-study.html','Bowling Green','Lawn Maintenance','Bowling Green Lawn Maintenance Planning Example','The property needed dependable mowing, trimming, and bed upkeep so the outside stayed clean during the growing season.','Terramorph defines route fit, frequency, access, trimming details, bed maintenance needs, and seasonal cleanup add-ons.','A simpler maintenance plan keeps curb appeal steady without the owner chasing one-off work.','real-lawn.webp'),
        ('holland-standing-water-case-study.html','Holland','Drainage Solutions','Holland Standing Water Planning Example','A flat area of lawn stayed wet after storms, limiting use and making maintenance harder.','Terramorph checks roof water, soil compaction, low spots, slope, discharge routes, and whether grading or drainage lines fit the property.','A clearer path to dry the usable lawn area and protect nearby beds or hardscape edges.','real-drainage.webp'),
        ('waterville-outdoor-living-case-study.html','Waterville','Paver Patios and Hardscapes','Waterville Outdoor Living Planning Example','The backyard needed a more intentional gathering area that connected patio use, walkways, and landscape beds.','Terramorph maps traffic flow, seating, grill placement, drainage, lighting, bed transitions, and base prep before pricing the project.','A backyard plan feels designed instead of pieced together.','real-hardscape.webp?v=3.14'),
        ('whitehouse-new-construction-landscape-case-study.html','Whitehouse','Landscape Design','Whitehouse New Construction Landscape Planning Example','The home needed front and backyard landscaping after construction so the property felt finished and easier to maintain.','Terramorph reviews grade, soil, builder drainage, bed layout, plant choices, mulch or rock, sod edges, and maintenance goals.','A phased landscape plan improves curb appeal while accounting for drainage and long-term upkeep.','real-entry.webp?v=3.14'),
        ('oregon-seasonal-cleanup-case-study.html','Oregon','Seasonal Cleanups','Oregon Seasonal Cleanup Planning Example','Leaf buildup, debris, and overgrown beds made the property look neglected after seasonal weather.','Terramorph scopes cleanup, trimming, debris removal, bed reset, mulch, and recurring maintenance needs.','A cleaner property reset prepares the yard for the next season.','real-mulch.webp'),
        ('rossford-walkway-patio-case-study.html','Rossford','Paver Patios and Hardscapes','Rossford Walkway and Patio Planning Example','The homeowner needed safer movement from the house to outdoor areas with a cleaner hardscape transition.','Terramorph evaluates grade, steps, walkway width, drainage, base prep, edge restraint, and how the hardscape connects to beds and lawn.','A more usable outdoor path and patio area improves curb appeal and reduces guesswork.','real-walkway.webp?v=3.14'),
    ]
    case_files = []
    for filename, city, service, title, problem, solution, outcome, image in case_studies:
        faqs = [(f'Does Terramorph handle {service.lower()} in {city}?', f'Yes. Terramorph serves {city} and surrounding Northwest Ohio communities with {service.lower()} and related outdoor property work.'), ('Can I send photos before an estimate?', 'Yes. Photos help Terramorph understand access, water movement, existing conditions, and project fit before follow-up.'), ('Is this an exact price example?', 'No. This is a planning example showing common local property problems and how Terramorph thinks through them. Final scope depends on the actual property.')]
        desc = f'{title}: local Terramorph project planning for {service.lower()} in {city}, Ohio.'
        body = f'''
<section class="page-hero premium-page-hero planning-example-hero"><div class="page-hero-image"><img src="assets/{image}" alt="{title}"></div><div class="hero-overlay"></div><div class="container page-hero-content"><p class="crumb"><a href="index.html">Home</a> / <a href="projects.html">Projects</a> / {city}</p><p class="eyebrow light">Local planning example</p><h1>{title}</h1><p>{desc}</p><div class="cta-row"><a class="btn btn-gold" href="#quote">Request Similar Work</a><a class="btn btn-outline-light" href="tel:{TEL}">Call {PHONE}</a></div></div></section>
{trust_band()}
<section class="section"><div class="container problem-grid"><div class="problem-card dark"><p class="eyebrow light">Problem</p><h2>{problem}</h2></div><div class="problem-card light-card"><p class="eyebrow">Terramorph approach</p><h2>{solution}</h2></div></div></section>
<section class="section clay-section"><div class="container local-grid"><div><p class="eyebrow">Expected outcome</p><h2>{outcome}</h2><p>This planning example shows the kind of details homeowners can have ready before a quote call: city, service need, photos, timeline, and the result they want.</p></div><div class="authority-list"><div><b>City</b><span>{city}, Ohio and nearby communities.</span></div><div><b>Service</b><span>{service}</span></div><div><b>Estimate path</b><span>Call {PHONE} with city, photos, timeline, and project notes.</span></div></div></div></section>
{faq_section(faqs)}
<section class="section quote-section"><div class="container quote-grid">{quote_form('Request Similar Terramorph Work')}<div class="cta-proof"><p class="eyebrow">Local proof</p><h2>Use this as a starting point for your own property.</h2>{review_stack(2)}</div></div></section>
'''
        (root / filename).write_text(page(title + ' | Terramorph', desc, body, schema_for(filename, title, desc, faqs, service)))
        case_files.append(filename)

    review_desc = 'Leave a Google review for Terramorph LLC or request more landscape, patio, drainage, lighting, cleanup, or maintenance work in Northwest Ohio.'
    review_body = f'''
<section class="page-hero premium-page-hero compact-hero"><div class="hero-overlay"></div><div class="container page-hero-content"><p class="crumb"><a href="index.html">Home</a> / Reviews</p><p class="eyebrow light">Terramorph reviews</p><h1>Help more Northwest Ohio homeowners find Terramorph.</h1><p>If Terramorph did strong work for you, a Google review helps local homeowners choose a reliable landscaping, patio, drainage, lighting, cleanup, or maintenance crew.</p><div class="cta-row"><a class="btn btn-gold" href="https://www.google.com/search?q=Terramorph+LLC+Perrysburg+OH+reviews" rel="noopener">Leave a Google Review</a><a class="btn btn-outline-light" href="contact.html">Request More Work</a></div></div></section>
{trust_band()}
<section class="section"><div class="container local-grid"><div><p class="eyebrow">Share your experience</p><h2>Reviews help neighbors choose a crew they can trust.</h2><p>This page gives customers a simple place to leave feedback after completed work or request more help from Terramorph.</p></div><div class="authority-list"><div><b>What to mention</b><span>City, service, result, communication, cleanup, and whether you would recommend Terramorph.</span></div><div><b>Helpful examples</b><span>Paver patio in Perrysburg, drainage solution in Maumee, landscaping in Toledo, lawn maintenance in Sylvania.</span></div><div><b>Photos help</b><span>Before/after photos can make reviews more useful for future customers.</span></div></div></div></section>
<section class="section quote-section"><div class="container quote-grid">{quote_form('Request Terramorph Service')}<div class="cta-proof"><p class="eyebrow">Customer proof</p><h2>Real reviews support every service page.</h2>{review_stack(4)}</div></div></section>
'''
    (root / 'reviews.html').write_text(page('Terramorph Reviews | Leave a Google Review', review_desc, review_body, schema_for('reviews.html', 'Terramorph Reviews', review_desc, DEFAULT_FAQS)))

    meta_landing_page('lp-backyard-patio-estimate.html', 'Backyard Patio Estimate', 'Backyard patio estimate', 'real-patio.webp?v=3.14', 'Turn the backyard into a place people actually use.', 'Request a free backyard patio assessment for pavers, layout, seating, grill zones, walkways, drainage, and finished outdoor living.', ['The backyard has no useful gathering space or the existing patio/walkway feels disconnected from how you want to live outside.', 'Terramorph reviews layout, access, base conditions, drainage, materials, lighting, and the way the patio should connect to the home.', 'A patio should feel planned before it is priced.', 'The best backyard patio starts with layout, water movement, materials, budget, and how the space will actually be used.'], 'Paver Patios and Hardscapes', 'Request My Backyard Patio Estimate', 'Free Backyard Patio Layout + Cost Assessment', ['No clear grill or seating area', 'Backyard feels disconnected from the house', 'Old concrete or uneven walkway', 'Need patio drainage planned before installation'], [('Use', 'How people will grill, sit, host, walk, and move through the backyard.'), ('Site', 'Door transitions, grade, drainage, soil, access, and nearby beds.'), ('Scope', 'Pavers, walkways, steps, edge details, lighting, and realistic budget range.')])
    meta_landing_page('lp-standing-water-yard.html', 'Standing Water Drainage Estimate', 'Standing water drainage estimate', 'real-drainage.webp', 'Stop planning your yard around puddles.', 'Request a free drainage assessment for standing water, soggy grass, downspout runoff, grading issues, and low spots.', ['Rain leaves the yard soft, muddy, unusable, or pooling near the house, patio, driveway, beds, or garage.', 'Terramorph checks where water starts, how it moves, where it can safely discharge, and which practical drainage options fit the property.', 'Standing water needs diagnosis, not guessing.', 'Clay soil, flat lots, runoff, and freeze-thaw make Northwest Ohio drainage a local problem.'], 'Drainage Solutions', 'Request My Standing Water Assessment', 'Free Standing Water + Yard Drainage Assessment', ['Puddles after normal rain', 'Soggy low spots or mud', 'Water near foundation, garage, patio, or beds', 'Downspouts dumping into bad areas'], [('Source', 'Roof water, neighbor runoff, slope, soil, low spots, or hardscape runoff.'), ('Route', 'Safe paths for water that do not create a new problem.'), ('Fix', 'Grading, swales, drains, buried lines, dry creek details, or landscape-based solutions.')])
    meta_landing_page('lp-curb-appeal-upgrade.html', 'Front Yard Curb Appeal Estimate', 'Front yard curb appeal estimate', 'real-entry.webp?v=3.14', 'Make the front of the home look finished.', 'Request a free curb appeal assessment for landscape beds, plantings, mulch, rock, edging, lighting, and front-entry upgrades.', ['The front yard looks tired, builder-grade, overgrown, empty, or disconnected from the house.', 'Terramorph reviews bed shape, plant selection, soil, sun, mulch versus rock, edging, lighting, and maintenance expectations.', 'Curb appeal should be simple to understand.', 'A good front yard upgrade makes the home feel cleaner, more premium, and easier to maintain.'], 'Landscape Design', 'Request My Curb Appeal Estimate', 'Free Front Yard Curb Appeal Assessment', ['Front beds look empty or overgrown', 'Old shrubs or messy edges', 'Not sure what plants fit the house', 'Want a cleaner entry and better first impression'], [('Street view', 'What people notice from the road, driveway, sidewalk, and front door.'), ('Conditions', 'Sun, shade, soil, water, existing plants, and maintenance level.'), ('Plan', 'Bed shape, plant palette, mulch or rock, edging, lighting, and phased budget.')])
    meta_landing_page('lp-spring-cleanup.html', 'Spring Cleanup Estimate', 'Spring cleanup estimate', 'real-mulch.webp', 'Reset the property before the season gets away from you.', 'Request a free spring cleanup estimate for leaves, debris, pruning, bed reset, mulch, trimming, and property prep.', ['Winter left sticks, leaves, dead plant material, messy beds, weeds, and overgrown edges behind.', 'Terramorph reviews cleanup scope, bed condition, debris removal, pruning needs, mulch, and whether maintenance should continue after the reset.', 'A clean spring start makes the rest easier.', 'The right cleanup gets the property ready for mowing, mulch, planting, outdoor use, and better curb appeal.'], 'Seasonal Cleanups', 'Request My Spring Cleanup Estimate', 'Free Spring Cleanup + Bed Reset Estimate', ['Leaves and sticks everywhere', 'Messy beds or old mulch', 'Bushes and edges need trimming', 'Want mowing/maintenance set up after cleanup'], [('Cleanup', 'Leaves, sticks, debris, dead plant material, weeds, and edge reset.'), ('Refresh', 'Mulch, rock, pruning, trimming, plant replacement, and bed shaping.'), ('Maintain', 'Optional recurring lawn care and bed upkeep after the reset.')])

    faq_topics = [
        ('paver-patio-cost-toledo-ohio.html', 'How Much Does a Paver Patio Cost in Toledo, Ohio?', 'Paver patio cost depends on size, access, base prep, drainage, steps, patterns, borders, and whether the project includes seating, fire pits, lighting, or beds.', 'Paver Patios and Hardscapes', 'real-patio.webp?v=3.14', ['What affects patio pricing?', 'Size, excavation, base depth, drainage, paver style, edge restraint, steps, access, and finishing details all affect the final estimate.', 'Why is a site review important?', 'Northwest Ohio clay soil, grade, and water movement can change what base preparation and drainage planning are needed.', 'Can Terramorph give a free patio estimate?', 'Yes. Send city, approximate size, photos, and goals through the quote form for the best next step.']),
        ('yard-drainage-cost-northwest-ohio.html', 'How Much Does Yard Drainage Cost in Northwest Ohio?', 'Drainage cost depends on the water source, outlet route, grade, soil, distance, access, and whether the property needs drains, swales, grading, or downspout routing.', 'Drainage Solutions', 'real-drainage.webp', ['Why is drainage pricing hard without seeing the yard?', 'A wet yard can come from roof water, neighbor runoff, low spots, clay soil, hardscape slope, or grade issues. The fix changes with the source.', 'Is every drainage fix a French drain?', 'No. Some properties need grading, swales, downspout extensions, catch basins, dry creek features, or a combination.', 'Can Terramorph inspect standing water?', 'Yes. Terramorph offers free drainage estimates for Wood and Lucas County properties.']),
        ('landscaping-cost-perrysburg-ohio.html', 'How Much Does Landscaping Cost in Perrysburg, Ohio?', 'Landscape pricing depends on bed size, plant selection, mulch or rock, edging, soil, existing removals, drainage, lighting, and whether the project is phased.', 'Landscape Design', 'real-entry.webp?v=3.14', ['What changes a landscape estimate?', 'Plant count, plant size, bed depth, edging, removals, mulch or rock, drainage, soil, lighting, and access all affect scope.', 'Can landscaping be phased?', 'Yes. Many homeowners start with front curb appeal, then add patios, lighting, drainage, or backyard areas later.', 'Does Terramorph handle design and install?', 'Yes. Terramorph can plan and install beds, plants, mulch, rock, edging, sod, and related outdoor upgrades.']),
        ('best-plants-for-ohio-clay-soil.html', 'Best Landscape Plants for Ohio Clay Soil and Wet Yards', 'Ohio clay soil can hold water, compact easily, and stress the wrong plants. Better plant choices depend on sun, drainage, mature size, and maintenance expectations.', 'Landscape Design', 'real-planting.webp', ['Why does clay soil matter?', 'Clay can stay wet, compact, and drain slowly, so plant selection and bed preparation matter more than just picking what looks good.', 'Can wet-yard planting replace drainage?', 'Sometimes plants help, but persistent standing water usually needs grade, routing, or drainage review too.', 'Can Terramorph recommend plants?', 'Yes. Terramorph reviews sun, soil, water, house style, and maintenance goals before recommending plantings.']),
        ('spring-cleanup-cost-toledo-ohio.html', 'Spring Cleanup Cost in Toledo and Northwest Ohio', 'Spring cleanup pricing depends on debris volume, leaf removal, pruning, bed reset, mulch, edging, hauling, and whether maintenance continues after the cleanup.', 'Seasonal Cleanups', 'real-mulch.webp', ['What is included in spring cleanup?', 'Common cleanup work includes sticks, leaves, dead plant material, bed reset, trimming, edging, debris hauling, and optional mulch.', 'When should cleanup be scheduled?', 'Early spring is best once winter debris is visible and before weeds and growth get ahead of the property.', 'Can cleanup turn into ongoing maintenance?', 'Yes. Terramorph can pair cleanup with mowing, trimming, bed maintenance, and seasonal follow-up.']),
        ('lawn-maintenance-cost-northwest-ohio.html', 'Lawn Maintenance Cost in Northwest Ohio', 'Lawn maintenance cost depends on property size, mowing frequency, trimming, edging, obstacles, bed upkeep, commercial needs, and seasonal cleanup add-ons.', 'Lawn Maintenance', 'real-lawn.webp', ['What affects mowing price?', 'Lot size, route fit, mowing frequency, trimming, edging, slopes, gates, obstacles, and cleanup expectations affect pricing.', 'Do you maintain commercial properties?', 'Yes. Terramorph can help with residential, commercial, and property-owner maintenance needs.', 'Can lawn care include beds?', 'Yes. Bed maintenance, weeding, trimming, cleanup, mulch, and seasonal resets can be scoped with mowing.']),
        ('outdoor-lighting-cost-ohio.html', 'Outdoor Lighting Cost for Patios, Walkways, and Landscaping in Ohio', 'Outdoor lighting cost depends on fixture count, transformer size, wire runs, controls, path safety, accent areas, and whether lighting is added during a larger project.', 'Outdoor Lighting', 'real-lighting.webp?v=3.14', ['What affects outdoor lighting cost?', 'Fixture type, number of lights, wire runs, transformer placement, controls, trenching, and design complexity all matter.', 'Can lighting be added to patios or beds?', 'Yes. Lighting often works best when planned with patios, walkways, beds, retaining walls, or curb appeal upgrades.', 'Does Terramorph install landscape lighting?', 'Yes. Terramorph handles outdoor lighting for paths, patios, entries, beds, and nighttime curb appeal.']),
        ('how-to-choose-landscaper-toledo.html', 'How to Choose a Landscaper in Toledo, Perrysburg, Maumee, and Northwest Ohio', 'The best landscaper should understand local soil, drainage, maintenance, hardscapes, communication, cleanup, reviews, and how services connect across the whole property.', 'Landscape Design', 'real-hero.webp', ['What should homeowners look for?', 'Look for local proof, reviews, clear estimates, professional communication, drainage awareness, photos, and a team that thinks through the whole property.', 'Why does local experience matter?', 'Northwest Ohio clay soil, flat lots, freeze-thaw, rain, and seasonal maintenance needs affect outdoor work.', 'Can Terramorph handle multiple services?', 'Yes. Terramorph connects design, patios, drainage, lighting, cleanup, lawn maintenance, and other property services.']),
    ]
    faq_files = []
    for filename, title, intro, service, image, qa in faq_topics:
        q1, a1, q2, a2, q3, a3 = qa
        faqs = [(q1, a1), (q2, a2), (q3, a3)]
        desc = title + ' Terramorph explains local factors and offers free estimates in Northwest Ohio.'
        body = f'''
<section class="page-hero premium-page-hero faq-hero"><div class="page-hero-image"><img src="assets/{image}" alt="{title}"></div><div class="hero-overlay"></div><div class="container page-hero-content"><p class="crumb"><a href="index.html">Home</a> / <a href="guides.html">Guides</a></p><p class="eyebrow light">Local project guide</p><h1>{title}</h1><p>{intro}</p><div class="cta-row"><a class="btn btn-gold" href="#quote">Request a Free Estimate</a><a class="btn btn-outline-light" href="tel:{TEL}">Call {PHONE}</a></div></div></section>
{trust_band()}
<section class="section"><div class="container local-grid"><div><p class="eyebrow">Short answer</p><h2>{intro}</h2><p>Online ranges are usually too broad because local soil, access, grade, drainage, materials, and property condition matter. Terramorph uses a real property review to turn broad ranges into a practical next step.</p></div><div class="authority-list"><div><b>{q1}</b><span>{a1}</span></div><div><b>{q2}</b><span>{a2}</span></div><div><b>{q3}</b><span>{a3}</span></div></div></div></section>
{faq_section(faqs)}
<section class="section quote-section"><div class="container quote-grid">{quote_form('Request a Free Terramorph Estimate')}<div class="cta-proof"><p class="eyebrow">Why ask Terramorph</p><h2>Local estimates beat generic online ranges.</h2>{review_stack(2)}</div></div></section>
'''
        (root / filename).write_text(page(title + ' | Terramorph', desc, body, schema_for(filename, title, desc, faqs, service)))
        faq_files.append(filename)

    guide_links = ''.join(
        f'<a class="guide-card faq-expansion-card" href="{filename}"><span>Helpful local guide</span><h3>{title}</h3><p>{intro}</p><b>Read answer &rarr;</b></a>'
        for filename, title, intro, service, image, qa in faq_topics
    )
    guides_page = root / 'guides.html'
    guides_html = guides_page.read_text()
    if 'V3.45 FAQ expansion' not in guides_html:
        section = f'<section class="section guide-index-section v345-faq-expansion"><div class="container section-heading compact"><p class="eyebrow">Project planning answers</p><h2>Cost, comparison, and local property questions homeowners ask before they request a quote.</h2></div><div class="container guide-grid">{guide_links}</div></section>'
        guides_html = guides_html.replace('<section class="section quote-section">', section + '\n<section class="section quote-section">')
        guides_page.write_text(guides_html)

    city_cards = ''.join(
        f'<a class="guide-card city-service-card" href="{name}"><span>Local service area</span><h3>{name.replace("-", " ").replace(".html", "").title()}</h3><p>Terramorph service information for this city and outdoor project type.</p><b>Open local page &rarr;</b></a>'
        for name in extra_city_pages
    )
    case_cards = ''.join(
        f'<a class="guide-card planning-example-card" href="{filename}"><span>{city} &middot; {service}</span><h3>{title}</h3><p>{problem}</p><b>View case study &rarr;</b></a>'
        for filename, city, service, title, problem, solution, outcome, image in case_studies
    )
    service_areas = root / 'service-areas.html'
    service_html = service_areas.read_text()
    if 'V3.45 expanded service area pages' not in service_html:
        section = f'<section class="section guide-index-section v345-expanded-service-pages"><div class="container section-heading compact"><p class="eyebrow">More service areas</p><h2>Local service information by city and project type.</h2><p>Homeowners in Sylvania, Bowling Green, Holland, Waterville, Whitehouse, Oregon, and Rossford can review the most relevant Terramorph services before requesting an estimate.</p></div><div class="container guide-grid">{city_cards}</div></section>'
        service_html = service_html.replace('<section class="section quote-section">', section + '\n<section class="section quote-section">')
        service_areas.write_text(service_html)
    projects_page = root / 'projects.html'
    projects_html = projects_page.read_text()
    if 'V3.45 local case studies' not in projects_html:
        section = f'<section class="section guide-index-section v345-case-studies"><div class="container section-heading compact"><p class="eyebrow">Local planning examples</p><h2>Common outdoor project scenarios around Northwest Ohio.</h2><p>Each example shows a typical property problem, how Terramorph would think through the scope, and what to include when requesting an estimate.</p></div><div class="container guide-grid">{case_cards}</div></section>'
        projects_html = projects_html.replace('<section class="section transformation-section proof-gallery-section">', section + '\n<section class="section transformation-section proof-gallery-section">')
        projects_page.write_text(projects_html)

    support_pages = [
        ('faq.html', 'Terramorph FAQ Hub', 'Answers about landscaping, patios, drainage, lighting, cleanups, maintenance, estimates, service areas, and project planning in Northwest Ohio.', 'FAQ hub', 'The questions homeowners ask before hiring Terramorph.', 'Use this hub to compare services, understand the estimate process, and decide what details to send before requesting a free quote.', 'real-hero.webp', DEFAULT_FAQS + [
            ('What makes Terramorph different from a typical landscaper?', 'Terramorph connects design, drainage, hardscapes, lighting, maintenance, and cleanup so outdoor projects are planned around the whole property instead of one isolated task.'),
            ('Why does Northwest Ohio experience matter?', 'Clay soil, flat grading, freeze-thaw cycles, heavy rain, mature neighborhoods, and new-construction lots all change how landscapes, patios, and drainage should be planned.'),
            ('What should I include in a quote request?', 'Include city, address, service type, timeline, photos, budget range if known, and what outcome you want from the project.'),
            ('Does Terramorph serve Perrysburg?', 'Yes. Perrysburg is a core Terramorph service area along with Toledo, Maumee, Sylvania, Rossford, Oregon, Waterville, Whitehouse, Bowling Green, Wood County, and Lucas County.')
        ]),
        ('process.html', 'Terramorph Process', 'How Terramorph estimates, plans, schedules, builds, cleans up, and follows through on landscape, patio, drainage, lighting, and maintenance projects.', 'Process', 'A clear process removes the contractor guesswork.', 'Terramorph’s best projects start with visible site conditions, a clear outcome, smart sequencing, and honest communication before work begins.', 'real-entry.webp?v=3.14', [('How does the estimate process work?', 'Send the property details and photos, then Terramorph reviews fit, site conditions, schedule, and the best next step for a quote or walkthrough.'), ('Do you inspect drainage before installing patios or beds?', 'Yes. Water movement, grade, soil, and runoff are reviewed when they affect the long-term result.'), ('What happens after approval?', 'The team confirms scope, schedule, materials, access, and cleanup expectations before production.'), ('Do you clean up after the job?', 'Yes. Professional cleanup and a final walkthrough are part of the expected project experience.')]),
        ('warranty.html', 'Terramorph Warranty & Workmanship', 'Terramorph workmanship expectations, material considerations, maintenance responsibilities, and what homeowners should understand before outdoor work begins.', 'Warranty and workmanship', 'Premium work should come with clear expectations.', 'This page explains what Terramorph controls, what materials and weather can affect, and how homeowners can protect the finished result.', 'real-hardscape.webp?v=3.14', [('Does outdoor work require maintenance?', 'Yes. Plants, beds, lighting, patios, drainage features, and lawns all perform best when maintained correctly after installation.'), ('Are materials covered by manufacturer terms?', 'Some pavers, lighting fixtures, plants, and materials may carry manufacturer or supplier terms. Terramorph can explain what applies to the selected scope.'), ('Why are drainage outcomes property-specific?', 'Drainage depends on grade, soil, outlet options, rainfall, neighboring runoff, and future property changes. A site-specific plan is important.'), ('What should I do if I have a concern after work?', 'Contact Terramorph quickly with photos and a clear description so the team can review the issue and recommend the right next step.')]),
        ('materials.html', 'Landscape Materials Guide', 'Guide to mulch, rock, pavers, edging, plants, lighting fixtures, base prep, drainage materials, and Northwest Ohio outdoor material decisions.', 'Materials guide', 'The right material choice depends on the property, not a trend.', 'Compare common landscape and hardscape materials through the lens of durability, maintenance, drainage, curb appeal, and Northwest Ohio weather.', 'real-patio.webp?v=3.14', [('Is mulch or rock better?', 'Mulch often supports plant health and lower upfront cost; rock can reduce refresh frequency but needs fabric, edging, and plant/heat planning.'), ('What matters most for paver patios?', 'Base prep, compaction, drainage, edge restraint, paver selection, and freeze-thaw planning matter more than choosing by color alone.'), ('What plants work best in clay soil?', 'Plant choice depends on sun, drainage, mature size, maintenance level, and whether the bed needs soil improvement or drainage correction.'), ('Can outdoor lighting be added later?', 'Yes, but lighting is often cleaner and more efficient when planned with patios, walkways, retaining details, and landscape beds.')]),
        ('financing.html', 'Landscape Project Budgeting', 'How to budget and phase landscaping, patio, drainage, lighting, cleanup, and maintenance work with Terramorph in Northwest Ohio.', 'Budgeting and phasing', 'A premium outdoor plan can be built in smart phases.', 'This page helps homeowners think through must-fix issues, curb appeal wins, outdoor living upgrades, and maintenance before requesting an estimate.', 'real-lighting.webp?v=3.14', [('Can landscaping be phased?', 'Yes. Many homeowners start with drainage or front curb appeal, then phase patios, lighting, backyard work, and maintenance.'), ('What should be prioritized first?', 'Problems that can damage or limit use, such as drainage and grading, should usually be addressed before purely cosmetic upgrades.'), ('Does Terramorph publish fixed prices?', 'No. Site conditions change scope significantly, so Terramorph uses property-specific estimates instead of generic price menus.'), ('Can I share a target budget?', 'Yes. A target range helps Terramorph recommend the smartest scope, phasing, and materials for the property.')]),
        ('team.html', 'Terramorph Team & Standards', 'Meet the Terramorph standard for communication, jobsite care, reviews, local knowledge, and premium outdoor work in Northwest Ohio.', 'Team standards', 'Trust starts with who shows up and how the work is handled.', 'Terramorph’s service standard centers on communication, property respect, clean work, and practical local judgment.', 'real-lawn.webp', [('Who leads Terramorph projects?', 'Terramorph is a local Northwest Ohio outdoor services company led by Ty and the Terramorph crew.'), ('What standards matter on the job?', 'Communication, punctuality, property care, clean edges, correct materials, cleanup, and follow-through all matter.'), ('Why do team standards matter?', 'Homeowners need clear evidence of trust, process, service fit, and local reputation before choosing a contractor.'), ('How can customers help the team quote faster?', 'Send photos, city, access notes, desired outcome, and timeline in the request form.')]),
        ('community.html', 'Terramorph in Northwest Ohio', 'Terramorph service-area commitment, local property knowledge, neighborhoods served, and outdoor project priorities across Wood and Lucas County.', 'Community and service area', 'Built for Perrysburg, Toledo, Wood County, and Lucas County properties.', 'This page reinforces where Terramorph works, what local conditions matter, and why neighborhood-specific judgment improves outdoor results.', 'real-hero.webp', [('What communities does Terramorph serve?', 'Terramorph serves Perrysburg, Toledo, Maumee, Sylvania, Rossford, Oregon, Waterville, Whitehouse, Bowling Green, Wood County, Lucas County, and nearby Northwest Ohio areas.'), ('Why does local geography matter?', 'Flat lots, clay soil, mature trees, new construction grading, river-area moisture, and lake-effect weather can all affect outdoor work.'), ('Does Terramorph work on both homes and businesses?', 'Yes. Terramorph can review residential, commercial, and property-owner outdoor service needs.'), ('How should I choose a local landscaper?', 'Look for real reviews, project photos, clear services, local explanations, direct estimate paths, and evidence they understand the property conditions.')]),
        ('before-after-gallery.html', 'Before and After Landscape Gallery', 'Terramorph project gallery for patios, drainage, front yard curb appeal, lighting, maintenance, cleanups, and landscape transformations in Northwest Ohio.', 'Before and after gallery', 'Visual proof helps homeowners and AI systems trust the work.', 'Use this gallery page as the central proof hub for real project photos, planning examples, service categories, and quote paths.', 'real-patio.webp?v=3.14', [('Why does project proof matter?', 'Photos show service fit, quality expectations, and the type of outdoor work Terramorph can handle.'), ('Can I request similar work?', 'Yes. Use the quote form and mention the photo or project type that matches your property goal.'), ('Should I send photos of my property?', 'Yes. Before photos help Terramorph understand existing conditions and recommend a better next step.'), ('Are these exact prices?', 'No. Photos show project types and outcomes; exact scope depends on the actual property.')]),
        ('tree-care-northwest-ohio.html', 'Tree & Shrub Care in Northwest Ohio', 'Tree and shrub trimming, pruning, bed cleanup, overgrowth control, plant health observations, and seasonal landscape care considerations in Northwest Ohio.', 'Tree and shrub care', 'Clean pruning and trimming can change the whole property.', 'Terramorph can review trimming, pruning, overgrowth, bed resets, cleanup, and related landscape maintenance needs as part of a broader property plan.', 'real-mulch.webp', [('Does Terramorph trim shrubs and bushes?', 'Yes. Shrub trimming, spring pruning, overgrowth cleanup, and bed reset work can be scoped with seasonal cleanup or maintenance.'), ('Do you diagnose tree diseases?', 'Terramorph can observe visible issues and recommend next steps, but specialized arborist diagnosis may be needed for complex tree health problems.'), ('When should shrubs be trimmed?', 'Timing depends on plant type, bloom cycle, property goals, and whether the work is part of spring or fall cleanup.'), ('Can trimming be combined with mulch?', 'Yes. Trimming, bed edging, debris removal, and mulch often make sense together.')]),
        ('holiday-lighting.html', 'Holiday Lighting in Northwest Ohio', 'Holiday lighting planning, installation considerations, safety, property access, and seasonal outdoor service requests from Terramorph in Northwest Ohio.', 'Holiday lighting', 'Seasonal lighting should look clean and be handled safely.', 'Terramorph can review holiday lighting requests alongside outdoor lighting, cleanup, maintenance, and seasonal property needs.', 'real-lighting.webp?v=3.14', [('Does Terramorph offer holiday lighting?', 'Holiday lighting can be requested through Terramorph for review based on schedule, property fit, access, and service availability.'), ('What details should I send?', 'Send property photos, roofline or landscape areas, timeline, address, and whether removal/storage support is needed.'), ('Can holiday lighting pair with outdoor lighting?', 'Yes. Permanent outdoor lighting and seasonal holiday lighting can be discussed together when planning nighttime curb appeal.'), ('When should I request holiday lighting?', 'Request early before seasonal schedules fill, especially for larger homes or commercial properties.')]),
    ]
    support_files = []
    for filename, title, desc, eyebrow, headline, intro, image, faqs in support_pages:
        detail_cards = ''.join(f'<div><b>{q}</b><span>{a}</span></div>' for q, a in faqs[:4])
        body = f'''\n<section class="page-hero premium-page-hero support-page-hero"><div class="page-hero-image"><img src="assets/{image}" alt="{title} by Terramorph"></div><div class="hero-overlay"></div><div class="container page-hero-content"><p class="crumb"><a href="index.html">Home</a> / {eyebrow}</p><p class="eyebrow light">{eyebrow}</p><h1>{headline}</h1><p>{intro}</p><div class="cta-row"><a class="btn btn-gold" href="#quote">Request a Free Estimate</a><a class="btn btn-outline-light" href="tel:{TEL}">Call {PHONE}</a></div></div></section>\n{trust_band()}\n<section class="section"><div class="container local-grid"><div><p class="eyebrow">Why this matters</p><h2>{desc}</h2><p>These details help homeowners compare outdoor service options and choose a clear next step near Perrysburg, Toledo, and Northwest Ohio.</p></div><div class="authority-list">{detail_cards}</div></div></section>\n{faq_section(faqs)}\n<section class="section quote-section"><div class="container quote-grid">{quote_form('Request a Free Terramorph Estimate')}<div class="cta-proof"><p class="eyebrow">Trust signal</p><h2>Clear information before the call helps homeowners choose with confidence.</h2>{review_stack(3)}</div></div></section>\n'''
        (root / filename).write_text(page(title + ' | Terramorph', desc, body, schema_for(filename, title, desc, faqs)))
        support_files.append(filename)

    support_cards = ''.join(f'<a class="guide-card support-card" href="{filename}"><span>Trust resource</span><h3>{title}</h3><p>{desc}</p><b>Open resource &rarr;</b></a>' for filename, title, desc, eyebrow, headline, intro, image, faqs in support_pages)
    guides_page = root / 'guides.html'
    guides_html = guides_page.read_text()
    if 'v346-trust-resource-hub' not in guides_html:
        section = f'<section class="section guide-index-section v346-trust-resource-hub"><div class="container section-heading compact"><p class="eyebrow">Trust resources</p><h2>Process, warranty, materials, budgeting, FAQ, team standards, and local proof.</h2><p>These pages answer the questions homeowners ask before choosing Terramorph for outdoor work.</p></div><div class="container guide-grid">{support_cards}</div></section>'
        guides_html = guides_html.replace('<section class="section quote-section">', section + '\n<section class="section quote-section">')
        guides_page.write_text(guides_html)

    authority_pages = [
        ('services.html','Terramorph Services','Complete Terramorph service hub for landscape design, paver patios, drainage, lighting, lawn maintenance, cleanups, retaining walls, snow removal, sod, mulch, and commercial outdoor work.','Services hub','Outdoor services for Northwest Ohio properties.','Terramorph plans and installs outdoor upgrades around the whole property: curb appeal, water movement, hardscapes, maintenance, lighting, and seasonal needs.','real-hero.webp','Outdoor Services'),
        ('case-studies.html','Terramorph Case Studies','Planning examples and local proof for Terramorph landscaping, patios, drainage, lawn maintenance, cleanups, and outdoor living projects in Northwest Ohio.','Case-study hub','Local project proof by city and service.','Use these examples to understand how Terramorph diagnoses property problems, scopes the work, and ties services together for better outdoor results.','real-patio.webp?v=3.14','Project Proof'),
        ('retaining-walls.html','Retaining Walls Northwest Ohio','Retaining wall planning, drainage, grading, steps, soil pressure, patio transitions, and landscape structure for Northwest Ohio homes.','Retaining walls','Retaining walls should solve grade problems, not create drainage problems.','Terramorph reviews slope, water, soil, wall purpose, access, and surrounding hardscape or landscape work before scoping retaining wall projects.','real-retaining.webp','Retaining Walls'),
        ('retaining-walls-toledo-ohio.html','Retaining Walls in Toledo, OH','Retaining wall planning and estimates for Toledo yards with slopes, grade changes, patios, beds, steps, drainage, and outdoor living transitions.','Toledo retaining walls','Retaining walls in Toledo need drainage and freeze-thaw planning.','Terramorph reviews grade, soil, runoff, access, wall height, nearby patios, and bed transitions before recommending a retaining wall scope.','real-retaining.webp','Retaining Walls'),
        ('retaining-walls-perrysburg-ohio.html','Retaining Walls in Perrysburg, OH','Retaining wall planning and estimates for Perrysburg properties needing grade control, outdoor living support, bed structure, steps, and drainage awareness.','Perrysburg retaining walls','A Perrysburg retaining wall should fit the property plan.','Terramorph scopes retaining walls around grade, drainage, soil, patio connections, lawn transitions, and long-term maintenance expectations.','real-retaining.webp','Retaining Walls'),
        ('outdoor-living.html','Outdoor Living Spaces Northwest Ohio','Outdoor living design for patios, fire pits, seating areas, outdoor kitchens, lighting, walkways, and landscape integration in Northwest Ohio.','Outdoor living','Outdoor living works best when layout, drainage, lighting, and materials are planned together.','Terramorph helps homeowners turn backyards into usable spaces with patio planning, hardscape details, lighting, beds, and water movement considered upfront.','real-hardscape.webp?v=3.14','Outdoor Living'),
        ('outdoor-kitchens-toledo-ohio.html','Outdoor Kitchens in Toledo, OH','Outdoor kitchen planning for Toledo patios, grill zones, seating, lighting, hardscape transitions, drainage, and backyard entertainment spaces.','Outdoor kitchens','An outdoor kitchen needs more than a grill location.','Terramorph reviews patio layout, access, utilities coordination, drainage, seating, lighting, and how the kitchen fits the full backyard plan.','real-hardscape.webp?v=3.14','Outdoor Kitchens'),
        ('fire-pit-installation-toledo-ohio.html','Fire Pit Installation in Toledo, OH','Fire pit area planning for Toledo backyards including paver patios, seating zones, walkways, drainage, lighting, and outdoor living flow.','Fire pits','A fire pit should feel built into the backyard, not dropped into it.','Terramorph scopes fire pit areas around seating, wind, safety clearances, patio layout, drainage, walkways, and lighting.','real-patio.webp?v=3.14','Fire Pits'),
        ('landscape-lighting-toledo-ohio.html','Landscape Lighting in Toledo, OH','Landscape lighting for Toledo homes, patios, walkways, entries, beds, security visibility, nighttime curb appeal, and outdoor living spaces.','Toledo landscape lighting','Lighting changes how the property feels after dark.','Terramorph plans low-voltage lighting around safety, curb appeal, patio use, path visibility, accent features, and future maintenance.','real-lighting.webp?v=3.14','Outdoor Lighting'),
        ('commercial-landscaping-toledo-ohio.html','Commercial Landscaping in Toledo, OH','Commercial landscaping, lawn maintenance, cleanups, bed upkeep, snow response, curb appeal, and exterior property care for Toledo businesses and property owners.','Commercial landscaping','Commercial properties need predictable exterior presentation.','Terramorph can review mowing, trimming, bed maintenance, seasonal cleanup, snow needs, access, route fit, and curb appeal priorities for Toledo properties.','real-maintenance.webp','Commercial Landscaping'),
        ('snow-removal-toledo-ohio.html','Snow Removal in Toledo, OH','Snow removal and winter access planning for Toledo homes, businesses, driveways, walkways, commercial lots, and property-owner needs.','Snow removal','Winter service is about safe access when weather hits.','Terramorph reviews driveway, walkway, parking, access, response expectations, and winter risk areas before confirming snow service fit.','snow-removal-truck.webp?v=3.17','Snow Removal'),
        ('sod-installation-toledo-ohio.html','Sod Installation in Toledo, OH','Sod installation planning for Toledo yards including grading, soil prep, watering expectations, drainage, lawn edges, and landscape transitions.','Sod installation','Sod only works when soil prep and water are handled correctly.','Terramorph reviews grade, soil, access, drainage, sunlight, watering expectations, and lawn edges before sod installation.','real-lawn.webp','Sod Installation'),
        ('mulch-installation-toledo-ohio.html','Mulch Installation in Toledo, OH','Mulch installation, bed edging, shrub trimming, cleanup, rock conversion, plant refresh, and curb appeal upgrades for Toledo properties.','Mulch installation','Fresh mulch works best after beds are cleaned and shaped.','Terramorph scopes mulch around bed depth, edging, weeds, plant health, drainage, cleanup, and the look homeowners want from the street.','real-mulch.webp','Mulch Installation'),
        ('spring-fall-cleanups-toledo-ohio.html','Spring & Fall Cleanups Toledo, OH','Spring and fall cleanup estimates for Toledo properties including leaves, sticks, bed reset, pruning, trimming, debris removal, mulch, and maintenance setup.','Seasonal cleanups','Cleanups reset the property before the season gets away.','Terramorph reviews debris, leaf load, bed condition, trimming, hauling, mulch, and whether recurring maintenance should follow the cleanup.','real-mulch.webp','Seasonal Cleanups'),
        ('paver-patio-cost-northwest-ohio.html','Paver Patio Cost Northwest Ohio','Paver patio cost factors in Northwest Ohio including size, base prep, drainage, access, paver style, steps, fire pits, lighting, and outdoor living details.','Patio cost guide','Patio prices change when base prep and drainage change.','This guide explains why Northwest Ohio patio estimates depend on clay soil, freeze-thaw, excavation, water movement, access, layout, and finish details.','real-patio.webp?v=3.14','Paver Patios and Hardscapes'),
        ('retaining-wall-cost-toledo-ohio.html','Retaining Wall Cost Toledo, OH','Retaining wall cost factors for Toledo properties including wall height, access, drainage, soil, materials, steps, grading, and landscape transitions.','Retaining wall cost','Retaining wall pricing depends on what the wall is holding back.','This guide explains the cost drivers homeowners should understand before requesting a retaining wall estimate in Toledo or Northwest Ohio.','real-retaining.webp','Retaining Walls'),
        ('landscape-design-cost-northwest-ohio.html','Landscape Design Cost Northwest Ohio','Landscape design and installation cost factors in Northwest Ohio including beds, plants, mulch, rock, edging, drainage, lighting, removals, and phasing.','Landscape cost guide','Landscape pricing depends on scope, materials, site conditions, and phasing.','Terramorph explains how to think through budget, curb appeal, plant choices, maintenance expectations, and connected services before requesting a quote.','real-entry.webp?v=3.14','Landscape Design'),
        ('french-drain-cost-toledo-ohio.html','French Drain Cost Toledo, OH','French drain and yard drainage cost factors for Toledo properties including water source, outlet, trench distance, soil, grading, access, and alternatives.','French drain cost','A French drain is not always the right drainage fix.','This guide helps homeowners understand when a French drain makes sense, what affects cost, and why diagnosis comes before installation.','real-drainage.webp','Drainage Solutions'),
        ('best-drainage-solutions-for-clay-soil-ohio.html','Best Drainage for Ohio Clay Soil','Best drainage options for Ohio clay soil, flat yards, soggy grass, downspout runoff, low spots, grading problems, and Northwest Ohio storm patterns.','Clay soil drainage','Clay soil drainage needs water routing, not guesswork.','Terramorph explains practical options for Northwest Ohio yards: grading, swales, buried lines, drains, catch basins, dry creek features, and landscape-based solutions.','real-drainage.webp','Drainage Solutions'),
        ('new-construction-landscaping-northwest-ohio.html','New Construction Landscaping Northwest Ohio','New construction landscaping for Northwest Ohio homes including grading review, drainage, front beds, sod, plantings, mulch, rock, patios, and phased curb appeal.','New construction landscaping','Builder-grade yards often need a real outdoor plan.','Terramorph reviews grade, drainage, soil, bed layout, plant selection, sod edges, and future patio or lighting phases for new homes.','real-entry.webp?v=3.14','Landscape Design'),
        ('low-maintenance-landscaping-northwest-ohio.html','Low-Maintenance Landscaping Northwest Ohio','Low-maintenance landscaping ideas for Northwest Ohio including plant selection, mulch vs rock, bed edging, native plants, drainage-aware design, and maintenance planning.','Low-maintenance landscaping','Low-maintenance does not mean no planning.','Terramorph designs around mature plant size, soil, water, sun, edging, mulch or rock, and realistic upkeep for Northwest Ohio properties.','real-planting.webp','Landscape Design'),
        ('landscape-maintenance-packages-northwest-ohio.html','Landscape Maintenance Packages Northwest Ohio','Landscape maintenance package planning for Northwest Ohio properties including mowing, trimming, edging, bed upkeep, seasonal cleanups, mulch, and commercial maintenance.','Maintenance packages','Reliable maintenance keeps the property looking finished.','Terramorph can review route fit, service frequency, trimming, bed care, seasonal cleanup, mulch refresh, and commercial property presentation needs.','real-maintenance.webp','Lawn Maintenance'),
    ]
    authority_files = []
    for filename, title, desc, eyebrow, headline, intro, image, service in authority_pages:
        faqs = [('Does Terramorph offer this service in Northwest Ohio?', f'Yes. Terramorph can review {service.lower()} requests in Perrysburg, Toledo, Wood County, Lucas County, and nearby Northwest Ohio communities.'),('What details should I send for an estimate?', 'Send city, address, photos, timeline, access notes, the problem you want solved, and any budget or phasing preference.'),('Why does a site review matter?', 'Outdoor work depends on grade, water movement, soil, access, materials, existing conditions, and how the property should function long term.'),('Can this be combined with other services?', 'Yes. Terramorph can scope related needs such as drainage, patios, beds, lighting, cleanups, maintenance, mulch, rock, sod, and seasonal work together when it makes sense.')]
        cards = ''.join(f'<div><b>{q}</b><span>{a}</span></div>' for q,a in faqs)
        related = ''.join(f'<a class="guide-card" href="{f}"><span>Related</span><h3>{t}</h3><p>{d}</p><b>Open page &rarr;</b></a>' for f,t,d,ey,h,i,img,svc in authority_pages if f != filename and (svc == service or ey in ['Services hub','Case-study hub']))[:2500]
        body = f'''\n<section class="page-hero premium-page-hero authority-page-hero"><div class="page-hero-image"><img src="assets/{image}" alt="{title} by Terramorph"></div><div class="hero-overlay"></div><div class="container page-hero-content"><p class="crumb"><a href="index.html">Home</a> / {eyebrow}</p><p class="eyebrow light">{eyebrow}</p><h1>{headline}</h1><p>{intro}</p><div class="cta-row"><a class="btn btn-gold" href="#quote">Request a Free Estimate</a><a class="btn btn-outline-light" href="tel:{TEL}">Call {PHONE}</a></div></div></section>\n{trust_band()}\n<section class="section"><div class="container local-grid"><div><p class="eyebrow">Answer first</p><h2>{desc}</h2><p>Terramorph uses real property conditions, local Northwest Ohio experience, project photos, named customer reviews, and a clear quote path to help homeowners make a confident decision before work begins.</p></div><div class="authority-list">{cards}</div></div></section>\n{faq_section(faqs)}\n<section class="section guide-index-section"><div class="container section-heading compact"><p class="eyebrow">Related resources</p><h2>Keep planning the right scope.</h2></div><div class="container guide-grid">{related}</div></section>\n<section class="section quote-section"><div class="container quote-grid">{quote_form('Request a ' + service + ' Estimate')}<div class="cta-proof"><p class="eyebrow">Why Terramorph</p><h2>Local proof, clean process, and practical recommendations before the work starts.</h2>{review_stack(3)}</div></div></section>\n'''
        (root / filename).write_text(page(title + ' | Terramorph', desc, body, schema_for(filename, title, desc, faqs, service)))
        authority_files.append(filename)

    # Link service and proof hubs into key discovery pages.
    for target, label in [('service-areas.html','v347-services-proof-links'),('projects.html','v347-services-proof-links'),('guides.html','v347-services-proof-links')]:
        path = root / target
        html = path.read_text()
        if label not in html:
            section = f'<section class="section guide-index-section {label}"><div class="container section-heading compact"><p class="eyebrow">Deeper planning</p><h2>Service, proof, and high-intent planning pages.</h2></div><div class="container guide-grid"><a class="guide-card" href="services.html"><span>Services</span><h3>All Terramorph Services</h3><p>Full service hub for landscaping, patios, drainage, lighting, walls, cleanups, sod, mulch, snow, and commercial work.</p><b>Open services &rarr;</b></a><a class="guide-card" href="case-studies.html"><span>Proof</span><h3>Case Study Hub</h3><p>Local planning examples by city and service.</p><b>Open case studies &rarr;</b></a><a class="guide-card" href="before-after-gallery.html"><span>Gallery</span><h3>Before and After Gallery</h3><p>Central project-photo proof hub.</p><b>Open gallery &rarr;</b></a></div></section>'
            html = html.replace('<section class="section quote-section">', section + '\n<section class="section quote-section">')
            path.write_text(html)

    # Paid landing pages and hypothetical planning examples stay available to
    # direct visitors but out of organic search until they have unique campaign
    # or completed-project evidence.
    sitemap_path = root / 'sitemap.xml'
    sitemap = sitemap_path.read_text()
    organic_authority_files = [name for name in authority_files if name != 'case-studies.html']
    extra_pages = extra_city_pages + faq_files + support_files + organic_authority_files + ['reviews.html']
    additions = ''
    for name in extra_pages:
        loc = BASE_URL + '/' + name
        if loc not in sitemap:
            additions += f'  <url><loc>{loc}</loc><changefreq>monthly</changefreq><priority>0.7</priority></url>\n'
    sitemap = sitemap.replace('</urlset>\n', additions + '</urlset>\n')
    sitemap_path.write_text(sitemap)

    image_entries = [
        ('assets/real-hero.webp', 'Terramorph landscaping project in Northwest Ohio'),
        ('assets/real-patio.webp', 'Paver patio and outdoor living project by Terramorph'),
        ('assets/real-drainage.webp', 'Drainage solution and grading work by Terramorph'),
        ('assets/real-entry.webp', 'Front entry landscaping and curb appeal by Terramorph'),
        ('assets/real-hardscape.webp', 'Hardscape and outdoor living installation by Terramorph'),
        ('assets/real-lawn.webp', 'Lawn maintenance and property care by Terramorph'),
        ('assets/real-mulch.webp', 'Mulch and bed refresh project by Terramorph'),
        ('assets/real-lighting.webp', 'Outdoor landscape lighting by Terramorph'),
        ('assets/real-walkway.webp', 'Walkway and patio transition by Terramorph'),
        ('assets/real-planting.webp', 'Landscape planting and bed installation by Terramorph'),
        ('assets/project-house.webp', 'Terramorph residential landscape project'),
        ('assets/project-lawn.webp', 'Terramorph lawn and landscape maintenance project'),
        ('assets/hero-landscape.webp', 'Terramorph landscape design hero image'),
        ('assets/patio.webp', 'Terramorph patio and hardscape service image'),
        ('assets/drainage.webp', 'Terramorph drainage solutions service image'),
        ('assets/lighting.webp', 'Terramorph outdoor lighting service image'),
        ('assets/outdoor-living.webp', 'Terramorph outdoor living service image'),
        ('assets/retaining.webp', 'Terramorph retaining wall service image'),
        ('assets/pond.webp', 'Terramorph pond and water feature service image'),
        ('assets/water-feature.webp', 'Terramorph water feature service image'),
    ]
    image_sitemap = '<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:image="http://www.google.com/schemas/sitemap-image/1.1">\n'
    for image_path, caption in image_entries:
        image_sitemap += f'  <url><loc>{BASE_URL}/</loc><image:image><image:loc>{BASE_URL}/{image_path}</image:loc><image:caption>{caption}</image:caption></image:image></url>\n'
    image_sitemap += '</urlset>\n'
    (root / 'image-sitemap.xml').write_text(image_sitemap)

    robots = root / 'robots.txt'
    robots_text = robots.read_text() if robots.exists() else 'User-agent: *\nAllow: /\n'
    if f'Sitemap: {BASE_URL}/image-sitemap.xml' not in robots_text:
        robots_text = robots_text.rstrip() + f'\nSitemap: {BASE_URL}/image-sitemap.xml\n'
        robots.write_text(robots_text)

    readme = root / 'README.md'
    text = readme.read_text()
    text = text.replace('# Terramorph V3.45 Website', '# Terramorph V3.48 Website')
    text = text.replace('## V3.45 priorities implemented', '## V3.48 priorities implemented')
    if 'V3.45 SEO/ad expansion' not in text:
        text += '''\n## V3.49 local growth/ad expansion\n- Added 28 more city/service pages for Sylvania, Bowling Green, Holland, Waterville, Whitehouse, Oregon, and Rossford.\n- Added 10 local planning example pages for common Northwest Ohio project scenarios.\n- Added a review request page to support Google Business Profile review generation.\n- Added 4 dedicated Meta ad landing pages for backyard patios, standing water, curb appeal, and spring cleanup.\n- Updated sitemap with all new indexable service, guide, planning, and ad landing pages while keeping thank-you/review notes excluded.\n- Added Google Business Profile, BBB, Facebook, and Instagram entity/proof links sitewide.\n- Added a website terms page and footer contact/proof links.\n'''
    text = text.replace(
        '- Updated sitemap with all new indexable service, guide, planning, and ad landing pages while keeping thank-you/review notes excluded.',
        '- Kept paid campaign pages and hypothetical planning examples out of the organic sitemap while leaving them available to direct visitors.'
    )
    readme.write_text(text)

    checklist = root / 'SEO_META_TRACKING_CHECKLIST.md'
    if checklist.exists():
        c = checklist.read_text()
        if 'V3.45 added landing pages' not in c:
            c += '''\n## V3.48 added landing pages\n\nRecommended Meta/Google campaign destinations added in this expansion:\n\n```text\nhttps://terramorphllc.com/lp-backyard-patio-estimate.html?utm_source=facebook&utm_medium=paid_social&utm_campaign=backyard_patio_estimate&utm_content={{ad.name}}\nhttps://terramorphllc.com/lp-standing-water-yard.html?utm_source=facebook&utm_medium=paid_social&utm_campaign=standing_water_drainage&utm_content={{ad.name}}\nhttps://terramorphllc.com/lp-curb-appeal-upgrade.html?utm_source=facebook&utm_medium=paid_social&utm_campaign=curb_appeal_upgrade&utm_content={{ad.name}}\nhttps://terramorphllc.com/lp-spring-cleanup.html?utm_source=facebook&utm_medium=paid_social&utm_campaign=spring_cleanup&utm_content={{ad.name}}\n```\n'''
            checklist.write_text(c)

    # Final metadata normalization keeps generated titles SERP-safe after all pages are written.
    import re, html
    title_overrides = {
        'landscaping-toledo-ohio.html':'Landscaping in Toledo, OH | Terramorph',
        'landscaping-perrysburg-ohio.html':'Landscaping in Perrysburg, OH | Terramorph',
        'landscaping-maumee-ohio.html':'Landscaping in Maumee, OH | Terramorph',
        'drainage-solutions-toledo-ohio.html':'Drainage Solutions in Toledo, OH | Terramorph',
        'drainage-solutions-perrysburg-ohio.html':'Drainage Solutions in Perrysburg, OH | Terramorph',
        'drainage-solutions-maumee-ohio.html':'Drainage Solutions in Maumee, OH | Terramorph',
        'paver-patios-toledo-ohio.html':'Paver Patios in Toledo, OH | Terramorph',
        'paver-patios-perrysburg-ohio.html':'Paver Patios in Perrysburg, OH | Terramorph',
        'paver-patios-maumee-ohio.html':'Paver Patios in Maumee, OH | Terramorph',
        'best-plants-for-ohio-clay-soil.html':'Best Plants for Ohio Clay Soil | Terramorph',
        'french-drains-vs-pop-up-emitters.html':'French Drains vs Pop-Up Emitters | Terramorph',
        'how-to-choose-landscaper-toledo.html':'How to Choose a Toledo Landscaper | Terramorph',
        'move-water-away-from-house.html':'Move Water Away From Your House | Terramorph',
        'mulch-vs-rock-landscape-beds.html':'Mulch vs Rock Landscape Beds | Terramorph',
        'native-plants-vs-lawn-ohio.html':'Native Plants vs Lawn in Ohio | Terramorph',
        'native-prairie-landscaping-ohio.html':'Native Prairie Landscaping Ohio | Terramorph',
        'northwest-ohio-yard-drainage-problems.html':'Why Northwest Ohio Yards Hold Water | Terramorph',
        'outdoor-lighting-cost-ohio.html':'Outdoor Lighting Cost in Ohio | Terramorph',
        'paver-patio-northwest-ohio-weather.html':'Paver Patios for Ohio Weather | Terramorph',
        'spring-cleanup-northwest-ohio.html':'Spring Cleanup Northwest Ohio | Terramorph',
        'whitehouse-new-construction-landscape-case-study.html':'Whitehouse New Construction Landscape | Terramorph',
    }
    desc_overrides = {
        'services.html':'Explore Terramorph landscaping, patios, drainage, lighting, maintenance, cleanups, walls, sod, mulch, snow, and commercial outdoor services in Northwest Ohio.'
    }
    for path in root.glob('*.html'):
        html_text = path.read_text()
        new_title = title_overrides.get(path.name)
        if new_title:
            html_text = re.sub(r'<title>.*?</title>', f'<title>{new_title}</title>', html_text, count=1, flags=re.S)
            escaped = html.escape(new_title, quote=True)
            html_text = re.sub(r'<meta property="og:title" content="[^"]*">', f'<meta property="og:title" content="{escaped}">', html_text)
            html_text = re.sub(r'<meta name="twitter:title" content="[^"]*">', f'<meta name="twitter:title" content="{escaped}">', html_text)
        if path.name in desc_overrides:
            escaped_desc = html.escape(desc_overrides[path.name], quote=True)
            html_text = re.sub(r'<meta name="description" content="[^"]*">', f'<meta name="description" content="{escaped_desc}">', html_text)
            html_text = re.sub(r'<meta property="og:description" content="[^"]*">', f'<meta property="og:description" content="{escaped_desc}">', html_text)
            html_text = re.sub(r'<meta name="twitter:description" content="[^"]*">', f'<meta name="twitter:description" content="{escaped_desc}">', html_text)
        html_text = html_text.replace('v=3.44', 'v=3.49').replace('v=3.48', 'v=3.49')
        path.write_text(html_text)

    return extra_pages
